package lk.SMP.Util;

public enum TextField {
    NON,NAME,EMAIL,ADDRESS,CONTACT,NIC,SALARY,AGE,PASSWORD,PRICE,AdminID,Username,Password, IDA,IDC,IDCS, DESCRIPTION, DATE, STATUS, IDD, AMOUNT, METHOD, IDP, PRODUCT, IDS, POSITION, IDE, DOUBLE,QTY,IDI
}
